extends:
  - google
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - prettier
rules:
  prettier/prettier:
    - error
    - singleQuote: true
      trailingComma: all
  require-jsdoc: 0
  valid-jsdoc: 0
