language: node_js
node_js:
- node
- lts/*
services:
- mongodb
env:
  secure: oOT0Z2q2GBKgDV0ypFiafc/NUa+t1G68kdjGSNQCAQ5Hh7VMr3HXAitopwKDj2JY7W0D589fU6BuBaKFM01Jya8FFF+oDlwKC2VQOUgl1KlRKilJlTK8XmTYCwMVK9mU3+iu9YNzPsKS+KGd15qWGTCQZk8v/m9Cn8XvZoE2nm748l9jOdF7f2GSQOYZxTfJqdtnGPUVSsETzQgfKoGxAVb0nTls0zR2rOwRa2OyTMhHbWi3aDPj6zDOELt1mhDr2GKcVMfsGiosTBR2nRZsjlB1ufChJFL/amUjUddCiTiO1GHxTORL27yRMoXuCnYef0pq+edyngXQZG690E27OZqi92d31XZqU+/cLX1J1YhsItcucgE8/KFQGa0esn1n5vW6j/GA0kVcI+FjsFW1ckrc8mQq2su/33DSXw2HPl2wpCH4iQrTNhYhMYoppxe9l5iDrO5Kl7/PAQ2DkLdG/4HhOTpbhqTOKF5XQYrO6I7uGiXSGiLI2lnvNmqYY9pgYfMCGqwwIl5K8BTGgHIZPvi4+Z88xH/KHVaWiKgWp9NVp7xAyx+9OlaSexfc5wXN1PXvJLwQX3VQrqVNkpp2CtfDi8GOPdIdaT6/QQNmMNKhRQTPxKJYcnuHrHJmyft/lGc1uOcJqtYmIWAoXEqokAg5IZNEzG3LtCWILJneFqs=
scripts:
- npm run lint
- npm run test
- npm run build
notifications:
  email: false
  slack:
    secure: eWpzZnQqukM/zjS5a6IgryeCg82yAUdhw9ptQt0m9Vzim88XH2+303cjyrWCQ+zHneUGcKVDKP99NPNf6GhdxL0/YSmrNhAH9P/MVq0/nm6Vqm6lrsPqWTU7CtMP0XPOoJgk1QK0ZLSqUT+jzo59ct3Evza+1CeRpHhwpD5FCwSwsRLRF4ycTERfJw/od0nZuL/Q4Zdzqz4iLaVhVMG1DkrfnNei6Uj7BvgABpsO7DoWsS5Neu0u+F4n+0Tmm+golVotqU70jU8Qw05IQxkFsFiFYNh4wcoUa/OcET1ABBU4GBc86Fqwq+pwWipU4HS9BQ2uyJTwRXrFNR3xnOt5gp1sEtMVkvHMZ6gaA6jEC/uifGlDm+TnUzsjean33t4AYVrw3J9EA9E+d2YXgJQjffK/PGMc3zRDIxOYYzXjKGxRLvcNIBVfRyOoFqKCiwHrunqgdb6vMvhPA9bH1WtZmyNPkQ3umdZ1vodQo+J3zzCpyVAGHenFUhuMya/U4cdrOoD73J4r+t1FIfGM9CwCcD1QfVvYmRqsH4i6NilBW0UHORU+Z4SYLpeTZWF/oNyd20yiDgIL4WLR8ae87gfpx76FXYr65yC+SjtadGTAf2zKUhgdPcg8D7BnPjBfXCZ6c+XrhP6qKK04Wjwu+vTZcSGwylj8JQgWBFdTObuz0Dg=
